Weights & Biases tracking enabled.
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
/scratch/md5121/okhatisathi/tacotron2/stft.py:67: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = pad_center(fft_window, filter_length)
/scratch/md5121/okhatisathi/tacotron2/layers.py:51: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=8000.0 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  sampling_rate, filter_length, n_mel_channels, mel_fmin, mel_fmax)
Epoch: 0
Train loss 0 45.240196 Grad Norm 14.126908 1.71s/it
Validation loss 0: 33.322186
Traceback (most recent call last):
  File "<ipython-input-6-f19ded8726e7>", line 37, in <module>
    use_wandb=use_wandb
  File "/scratch/md5121/okhatisathi/tacotron2/train.py", line 262, in train
    'accuracy': accuracy.item(),  # If you compute accuracy
NameError: name 'accuracy' is not defined
Saving model and optimizer state at iteration 0 to ./outdir/checkpoint_0
An error occurred during training: name 'accuracy' is not defined